### ISSUE TITLE
AWS lambda warmup

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-chatbot-old#10]
@talltom on https://github.com/urbanriskmap/twitter-dm-bot-lamda did you notice any issues with lambda warmup time being an issue wrt twitter's strict requirement to respond to the webhook get in <1s? They request that every 24h but that's not often enough to keep the lambda warm, and when the lambda I've got here for the webhook fires up cold it's too slow. To fix I'm using the [serverless-plugin-warmup](https://github.com/FidelLimited/serverless-plugin-warmup) to keep our lambda warm. If I have to move the lambda outside of the US then this problem will become even worse (finite speed of light is such a pain in the bum).

**Comment by talltom** [comment]
Hi @matthewberryman - no I didn't see this as a problem. Does changing the Lambda timeout parameter help? Running a warmup script is probably a good idea though.

**Comment by JohnCalhoun** [comment]
found a write up of some lambda cold start experiments 
https://read.acloud.guru/does-coding-language-memory-or-package-size-affect-cold-starts-of-aws-lambda-a15e26d12c76

highlights 
- use nodejs or python
- the more memory the lambda has the faster the cold start(?)

**Comment by matthewberryman** [comment]
Thanks @JohnCalhoun - very useful stats there! I'm now using node.js (in the https://github.com/MSFREACH/msf-reach-chatbot/tree/twitter-webhook-js branch), so from a language perspective we're good, and I will try increasing the memory size assigned to see if that helps. The warmup serverless plugin has been working well but would be good to use that trigger less often (with a view to keeping costs down).

@talltom we're not hitting the AWS limit, this is a Twitter timeout limit.
