### ISSUE TITLE
integrate into social media platforms

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-chatbot-old#7]

**Comment by matthewberryman** [comment]
Integration done for Facebook with e2ba5b4f9264470d8bbf12847772582da48f9df7 plus configuration in console per http://docs.aws.amazon.com/lex/latest/dg/fb-bot-association.html

**Comment by matthewberryman** [comment]
Integration for Twitter done in b0d950f6a6d76ed970b9ec928797986be36f20de 
Will require testing and also configuration in Twitter dev console.

**Comment by LucieGueuning** [comment]
- Facebook (messenger, WhatApps)
- Twitter (feed, message)
- Mail

cf. https://docs.google.com/spreadsheets/d/1fgFDKMzV5PqmtWkYNA2laB1Nt8IGzx43T9DFjiKbLUE/edit?usp=sharing

**Comment by matthewberryman** [comment]
Ok. We cannot do WhatsApp until if/when they release an official API.

**Comment by LucieGueuning** [comment]
For Twitter: Heads up on this request to get beta access to the Twitter direct message bot API, for it to work under @MSF_REACH. Note that under the organisational details I had to list MSF and their main twitter account @msf so you may get asked by the MSF social media team about this.

Code (untested until we get access, but based on working code)

**Comment by LucieGueuning** [comment]
For Twitter: beta API's approved. 

The chatbot is now working on Twitter after much debugging of interactions between Twitter, the bit of code that handles Twitter web hooks and the other parts of the chatbot code. 

To try it out please try sending a direct message to the @MSF_REACH account on Twitter. If you’ve already asked the bot something that, then don’t ask it the same / similar again, as the bot then hits a spam detection algorithm in Twitter’s servers and you won’t see a response, and if you don’t see a response then that’s the most likely reason why (bearing in mind I have already tested it from a few accounts through today, trying to take things slowly to not trigger it). I have raised an issue on GitHub about this for Tom’s advice on the possibility of getting the account / bot whitelisted.

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/35150514-907e80fe-fd12-11e7-92f0-988f5bd988b6.png)

Working well!

**Comment by LucieGueuning** [comment]
I’ve just got some new code up today in our dev environment https://dev.msf-reach.org/ that is now automatically adding entries into the chatbot for new and modified events (as they are modified going forwards) and just tried this out then successfully over the Twitter version of the bot (ignore the duplicate reply that is an unrelated known bug in the Twitter code elsewhere).

I still need to write a script to go back and add old events into the system and I’ll let you know when that’s done.

Tom—I will need to get you some configuration details for you to run with this locally (it’s off by default if you don’t have them), which I will do later today.

**Comment by LucieGueuning** [comment]
I have an initial import script and have imported from the dev database into the chatbot. There’s still some tidy up around how to handle spaces in names, geocoding, language translation, etc., as part of a general rethink we need to do around event names and metadata. This flows into other areas like display of events, twitter search, too, so it’s increasingly important. I will put some thought into this issue and then engage further with you on how to handle this, and is something we need to reflect on in the ethnographic research too.

**Comment by LucieGueuning** [comment]
Ok. I mainly want to focus on the chatbot stuff on the call which includes Twitter verification.
