### ISSUE TITLE
whitelisting / something else required?

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-chatbot-old#9]
Getting this back trying to send DMs
```json
{
  'code': 226, 
  'message': "This request looks like it might be automated. To protect our users from 
    spam and other malicious activity, we can't complete this action right now. 
    Please try again later."
}
```

@talltom is it just the case that we need whitelisting, or some other strategy? For now I have added a timestamp in in 96da512dcb9573c75cfa7c28b195fb5cb7e34722

**Comment by matthewberryman** [comment]
Even adding a timestamp isn't working around this. Will revert 96da512 in next commit.

**Comment by talltom** [comment]
@matthewberryman hmm...next step to try would be verifying the account (which also white lists I believe).

**Comment by matthewberryman** [comment]
I did a bit of searching around whitelisting and the error message (after fixing up some Twitter DM code in recent commits) and found this form https://help.twitter.com/forms/platform for app whitelisting - I will submit that form now. cc @LucieGueuning

**Comment by matthewberryman** [comment]
Have filed a report. @LucieGueuning you should expect an email in a day or three.

**Comment by matthewberryman** [comment]
@LucieGueuning any update?

**Comment by LucieGueuning** [comment]
cf. email forwarded. Please confirm
